### ISSUE TITLE
Gebruik meer classes

### ISSUE THREAD

**Issue by itsValyria** [zoepje/look-and-feel-living-styleguide#15]
Zodat je niet ineens onbedoeld twee zwarte divs hebt ;)

**Comment by zoepje** [comment]
Dit hebben we hier opgelost.

HTML:
https://github.com/zoepje/look-and-feel-living-styleguide/blob/9939dd5eb85ce8549001b41a36672e37916c0774/index.html#L72C1-L72C32

CSS:
https://github.com/zoepje/look-and-feel-living-styleguide/blob/9939dd5eb85ce8549001b41a36672e37916c0774/style.css#L62-L64C2
