### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by Ryank2004** [zoepje/look-and-feel-living-styleguide#16]
Misschien een section maken voor icons, zodat je dat hamburger icoontje wat je benoemd bij navigatie er in kan zetten. Zo kunnen mensen het direct copy pasten in hun code.

**Comment by zoepje** [comment]
Ja dit hebben we hier toegevoed.
https://github.com/zoepje/look-and-feel-living-styleguide/blob/101ef050fd29203bc583849b640e05026eb2773d/index.html#L478-L511
