### ISSUE TITLE
Voorbeelden toevoegen

### ISSUE THREAD

**Issue by zainablfz** [zoepje/look-and-feel-living-styleguide#17]
Laat bij elke component zien hoe deze eruit komt te zien.

**Comment by zoepje** [comment]
Dit hebben we gedaan.
https://github.com/zoepje/look-and-feel-living-styleguide/blob/bd177ea0901f836f0182c8d81ed238e5c0b0a7d2/index.html#L164

https://github.com/zoepje/look-and-feel-living-styleguide/blob/bd177ea0901f836f0182c8d81ed238e5c0b0a7d2/index.html#L208-L209

https://github.com/zoepje/look-and-feel-living-styleguide/blob/bd177ea0901f836f0182c8d81ed238e5c0b0a7d2/index.html#L273-L280
