### ISSUE TITLE
text content overflowed

### ISSUE THREAD

**Issue by koeenm** [zoepje/look-and-feel-living-styleguide#18]
jullie hebben heel veel goede en mooie code voorbeelden gebruikt, alleen past de code tekst bij het stukje grid niet in het component, dus komt de tekst tot buiten de box

**Comment by zoepje** [comment]
https://github.com/zoepje/look-and-feel-living-styleguide/blob/8cadb5033473f42ea6b7e1cf2129da8c1b6b1941/style.css#L48-L56

Dit hebben we opgelost door de sections grooter te maken.
