### ISSUE TITLE
Waarom hier 14px?

### ISSUE THREAD

**Issue by Knetters** [zoepje/look-and-feel-living-styleguide#23]
Het is gebruikelijk om niet lager dan 16px te gebruiken tenzij hier een hele goeie reden voor is. In het menu is het vaak wel handig om een goed leesbare grootte.

Ik zag het in het menu staan: https://github.com/zoepje/look-and-feel-living-styleguide/blob/9939dd5eb85ce8549001b41a36672e37916c0774/index.html#L166

**Comment by latoyaln** [comment]
Dit is aangepast naar 16 px
b6da1247b6ac95aa52f7a476f92431a9b1d25d2a
