### ISSUE TITLE
Als je headers standaard in caps wil hebben kan je text-transform: uppercase; gebruiken

### ISSUE THREAD

**Issue by Knetters** [zoepje/look-and-feel-living-styleguide#24]
Er zijn verschillende meningen over het gebruik van all caps. BEETJE AGRESSIEF!

Je zou echter wel text-transform: uppercase; op de heading in CSS kunnen zetten. Dan is alle tekst standaard in caps.

**Comment by zoepje** [comment]
Dit hebben we hier gedaan.
#34
