### ISSUE TITLE
Vervang px met em.

### ISSUE THREAD

**Issue by Knetters** [zoepje/look-and-feel-living-styleguide#25]
Probeer zo min mogelijk px te gebruiken en stap over naar eenheden zoals em, rem, wv of misschien wel %. Ik zag het hier bijvoorbeeld staan: 

https://github.com/zoepje/look-and-feel-living-styleguide/blob/9939dd5eb85ce8549001b41a36672e37916c0774/index.html#L255

**Comment by latoyaln** [comment]
Zoveel mogelijk px naar em of vh/vw veranderd
297c90f36a7adfa8a199ed8e04b4b3768d3b914e
